import argparse

import gradio as gr

from openvoice.app_service import OpenVoiceService, SynthesisRequest

service = OpenVoiceService()


def predict(prompt, style, audio_file_pth, agree):
    response = service.synthesize(
        SynthesisRequest(
            prompt=prompt,
            style=style,
            audio_file_path=audio_file_pth,
            agree=agree,
        )
    )

    if not response.success:
        gr.Warning(response.info)
        return response.info, None, None

    return response.info, response.output_audio_path, response.reference_audio_path


title = "MyShell OpenVoice"

description = """
We introduce OpenVoice, a versatile instant voice cloning approach that requires only a short audio clip from the reference speaker to replicate their voice and generate speech in multiple languages. OpenVoice enables granular control over voice styles, including emotion, accent, rhythm, pauses, and intonation, in addition to replicating the tone color of the reference speaker. OpenVoice also achieves zero-shot cross-lingual voice cloning for languages not included in the massive-speaker training set.
"""

markdown_table_v2 = """
<div align="center" style="margin-bottom: 2px;">

|               |               |               |              |
| :-----------: | :-----------: | :-----------: | :-----------: |
| **OpenSource Repo** | <div style='text-align: center;'><a style="display:inline-block,align:center" href='https://github.com/myshell-ai/OpenVoice'><img src='https://img.shields.io/github/stars/myshell-ai/OpenVoice?style=social' /></a></div> |  **Project Page** |  [OpenVoice](https://research.myshell.ai/open-voice) |

| | |
| :-----------: | :-----------: |
**Join the Community** |   [![Discord](https://img.shields.io/discord/1122227993805336617?color=%239B59B6&label=%20Discord%20)](https://discord.gg/myshell) |

</div>
"""
content = """
<div>
  <strong>If the generated voice does not sound like the reference voice, please refer to <a href='https://github.com/myshell-ai/OpenVoice/blob/main/docs/QA.md'>this QnA</a>.</strong> <strong>For multi-lingual & cross-lingual examples, please refer to <a href='https://github.com/myshell-ai/OpenVoice/blob/main/demo_part2.ipynb'>this jupyter notebook</a>.</strong>
  This online demo mainly supports <strong>English</strong>. The <em>default</em> style also supports <strong>Chinese</strong>. But OpenVoice can adapt to any other language as long as a base speaker is provided.
</div>
"""
wrapped_markdown_content = f"<div style='border: 1px solid #000; padding: 10px;'>{content}</div>"


examples = [
    [
        "今天天气真好，我们一起出去吃饭吧。",
        'default',
        "resources/demo_speaker1.mp3",
        True,
    ], [
        "This audio is generated by open voice with a half-performance model.",
        'whispering',
        "resources/demo_speaker2.mp3",
        True,
    ],
    [
        "He hoped there would be stew for dinner, turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick, peppered, flour-fattened sauce.",
        'sad',
        "resources/demo_speaker0.mp3",
        True,
    ],
]


def build_demo():
    with gr.Blocks(analytics_enabled=False, title=title) as demo:
        gr.Markdown(f"### Startup status\n`{service.startup_message}`")

        with gr.Row():
            with gr.Column():
                with gr.Row():
                    gr.Markdown(
                        """
                        ## <img src="https://huggingface.co/spaces/myshell-ai/OpenVoice/raw/main/logo.jpg" height="40"/>
                        """
                    )
                with gr.Row():
                    gr.Markdown(markdown_table_v2)
                with gr.Row():
                    gr.Markdown(description)
            with gr.Column():
                gr.Video('https://github.com/myshell-ai/OpenVoice/assets/40556743/3cba936f-82bf-476c-9e52-09f0f417bb2f', autoplay=True)

        with gr.Row():
            gr.HTML(wrapped_markdown_content)

        with gr.Row():
            with gr.Column():
                input_text_gr = gr.Textbox(
                    label="Text Prompt",
                    info="One or two sentences at a time is better. Up to 200 text characters.",
                    value="He hoped there would be stew for dinner, turnips and carrots and bruised potatoes and fat mutton pieces to be ladled out in thick, peppered, flour-fattened sauce.",
                )
                style_gr = gr.Dropdown(
                    label="Style",
                    info="Select a style of output audio for the synthesised speech. (Chinese only support 'default' now)",
                    choices=['default', 'whispering', 'cheerful', 'terrified', 'angry', 'sad', 'friendly'],
                    max_choices=1,
                    value="default",
                )
                ref_gr = gr.Audio(
                    label="Reference Audio",
                    info="Click on the ✎ button to upload your own target speaker audio",
                    type="filepath",
                    value="resources/demo_speaker2.mp3",
                )
                tos_gr = gr.Checkbox(
                    label="Agree",
                    value=False,
                    info="I agree to the terms of the cc-by-nc-4.0 license-: https://github.com/myshell-ai/OpenVoice/blob/main/LICENSE",
                )

                tts_button = gr.Button("Send", elem_id="send-btn", visible=True)

            with gr.Column():
                out_text_gr = gr.Text(label="Info")
                audio_gr = gr.Audio(label="Synthesised Audio", autoplay=True)
                ref_audio_gr = gr.Audio(label="Reference Audio Used")

                gr.Examples(
                    examples,
                    label="Examples",
                    inputs=[input_text_gr, style_gr, ref_gr, tos_gr],
                    outputs=[out_text_gr, audio_gr, ref_audio_gr],
                    fn=predict,
                    cache_examples=False,
                )
                tts_button.click(predict, [input_text_gr, style_gr, ref_gr, tos_gr], outputs=[out_text_gr, audio_gr, ref_audio_gr])

    return demo


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--share", action='store_true', default=False, help="make link public")
    args = parser.parse_args()

    service.bootstrap()
    demo = build_demo()
    demo.queue()
    demo.launch(debug=True, show_api=True, share=args.share)


if __name__ == "__main__":
    main()
